config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :performance_reviews
  resources :objectives
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  devise_for :users
  root to: "home#index" 

    # ... otras rutas ...


  

  #devise_for :users

  #root to: "home#index"
  #resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :performance_review
    belongs_to :author, class_name: 'User'
end

app/models/objective.rb
class Objective < ApplicationRecord
end

app/models/performance_review.rb
class PerformanceReview < ApplicationRecord
    belongs_to :user
    belongs_to :objective
end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to feedback_url(@feedback), notice: "Feedback was successfully created." }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to feedback_url(@feedback), notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy!

    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:performance_review_id, :author_id, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: %i[ show edit update destroy ]

  # GET /objectives or /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1 or /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives or /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to objective_url(@objective), notice: "Objective was successfully created." }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1 or /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to objective_url(@objective), notice: "Objective was successfully updated." }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1 or /objectives/1.json
  def destroy
    @objective.destroy!

    respond_to do |format|
      format.html { redirect_to objectives_url, notice: "Objective was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def objective_params
      params.require(:objective).permit(:title, :description, :due_date, :user_id)
    end
end

app/controllers/performance_reviews_controller.rb
class PerformanceReviewsController < ApplicationController
  before_action :set_performance_review, only: %i[ show edit update destroy ]

  # GET /performance_reviews or /performance_reviews.json
  def index
    @performance_reviews = PerformanceReview.all
  end

  # GET /performance_reviews/1 or /performance_reviews/1.json
  def show
  end

  # GET /performance_reviews/new
  def new
    @performance_review = PerformanceReview.new
  end

  # GET /performance_reviews/1/edit
  def edit
  end

  # POST /performance_reviews or /performance_reviews.json
  def create
    @performance_review = PerformanceReview.new(performance_review_params)

    respond_to do |format|
      if @performance_review.save
        format.html { redirect_to performance_review_url(@performance_review), notice: "Performance review was successfully created." }
        format.json { render :show, status: :created, location: @performance_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @performance_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performance_reviews/1 or /performance_reviews/1.json
  def update
    respond_to do |format|
      if @performance_review.update(performance_review_params)
        format.html { redirect_to performance_review_url(@performance_review), notice: "Performance review was successfully updated." }
        format.json { render :show, status: :ok, location: @performance_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @performance_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performance_reviews/1 or /performance_reviews/1.json
  def destroy
    @performance_review.destroy!

    respond_to do |format|
      format.html { redirect_to performance_reviews_url, notice: "Performance review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performance_review
      @performance_review = PerformanceReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def performance_review_params
      params.require(:performance_review).permit(:user_id, :objective_id, :rating, :comments)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/performance_reviews_helper.rb
module PerformanceReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feedbacks/_feedback.html.erb
<div id="<%= dom_id feedback %>">
  <p>
    <strong>Feedback y Retroalimentación:</strong>
    <%= feedback.performance_review_id %>
  </p>

  <p>
    <strong>Empleado:</strong>
    <%= feedback.author_id %>
  </p>

  <p>
    <strong>Contenido:</strong>
    <%= feedback.content %>
  </p>

</div>

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :evaluacionDesempeño, style: "display: block" %>
    <%= form.number_field :performance_review_id %>
  </div>

  <div>
    <%= form.label :empleado, style: "display: block" %>
    <%= form.number_field :author_id %>
  </div>

  <div>
    <%= form.label :observaciones, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Show this feedback", @feedback %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

app/views/feedbacks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Feedbacks</h1>

<div id="feedbacks">
  <% @feedbacks.each do |feedback| %>
    <%= render feedback %>
    <p>
      <%= link_to "Show this feedback", feedback %>
    </p>
  <% end %>
</div>

<%= link_to "New feedback", new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>Nueva Retroalimentación</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Lista", feedbacks_path %>
</div>

app/views/feedbacks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feedback %>

<div>
  <%= link_to "Edit this feedback", edit_feedback_path(@feedback) %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>

  <%= button_to "Destroy this feedback", @feedback, method: :delete %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="alert alert-success" role="alert">
    Bienvenido <%= current_user.email %>
    <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  </div>
<% else %>
  <%= button_to "Iniciar sesión", new_user_session_path, class: "btn btn-primary" %>
<% end %>

<h1>TalentColombia</h1>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Menú</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= objectives_path %>">Objetivos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= performance_reviews_path %>">Evaluaciones de Desempeño</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= feedbacks_path %>">Retroalimentación</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TalentColombia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

  </body>
</html>

app/views/objectives/_form.html.erb
<%= form_with(model: objective) do |form| %>
  <% if objective.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
        <% objective.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :empleado, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/objectives/_objective.html.erb
<div id="<%= dom_id objective %>">
  <p>
    <strong>Title:</strong>
    <%= objective.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= objective.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= objective.due_date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= objective.user_id %>
  </p>

</div>

app/views/objectives/edit.html.erb
<h1>Editing objective</h1>

<%= render "form", objective: @objective %>

<br>

<div>
  <%= link_to "Show this objective", @objective %> |
  <%= link_to "Back to objectives", objectives_path %>
</div>

app/views/objectives/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Objetivos</h1>

<div id="objectives">
  <% @objectives.each do |objective| %>
    <%= render objective %>
    <p>
      <%= link_to "Show this objective", objective %>
    </p>
  <% end %>
</div>

<%= link_to "New objective", new_objective_path %>

app/views/objectives/new.html.erb
<h1>Nuevo Objetivo</h1>

<%= render "form", objective: @objective %>

<br>

<div>
  <%= link_to "Lista Objetivos", objectives_path %>
</div>

app/views/objectives/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @objective %>

<div>
  <%= link_to "Edit this objective", edit_objective_path(@objective) %> |
  <%= link_to "Back to objectives", objectives_path %>

  <%= button_to "Destroy this objective", @objective, method: :delete %>
</div>

app/views/performance_reviews/_form.html.erb
<%= form_with(model: performance_review) do |form| %>
  <% if performance_review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(performance_review.errors.count, "error") %> prohibited this performance_review from being saved:</h2>

      <ul>
        <% performance_review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :usuario, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :objetivo, style: "display: block" %>
    <%= form.number_field :objective_id %>
  </div>

  <div>
    <%= form.label :clasificacion, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :comentarios, style: "display: block" %>
    <%= form.text_area :comments %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/performance_reviews/_performance_review.html.erb
<div id="<%= dom_id performance_review %>">
  <p>
    <strong>User:</strong>
    <%= performance_review.user_id %>
  </p>

  <p>
    <strong>Objective:</strong>
    <%= performance_review.objective_id %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= performance_review.rating %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= performance_review.comments %>
  </p>

</div>

app/views/performance_reviews/edit.html.erb
<h1>Editing performance review</h1>

<%= render "form", performance_review: @performance_review %>

<br>

<div>
  <%= link_to "Show this performance review", @performance_review %> |
  <%= link_to "Back to performance reviews", performance_reviews_path %>
</div>

app/views/performance_reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Performance reviews</h1>

<div id="performance_reviews">
  <% @performance_reviews.each do |performance_review| %>
    <%= render performance_review %>
    <p>
      <%= link_to "Show this performance review", performance_review %>
    </p>
  <% end %>
</div>

<%= link_to "New performance review", new_performance_review_path %>

app/views/performance_reviews/new.html.erb
<h1>Nueva evaluación de desempeño</h1>

<%= render "form", performance_review: @performance_review %>

<br>

<div>
  <%= link_to "Lista", performance_reviews_path %>
</div>

app/views/performance_reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @performance_review %>

<div>
  <%= link_to "Edit this performance review", edit_performance_review_path(@performance_review) %> |
  <%= link_to "Back to performance reviews", performance_reviews_path %>

  <%= button_to "Destroy this performance review", @performance_review, method: :delete %>
</div>